config/routes.rb
Rails.application.routes.draw do
  # create path to homepage
  root :to => 'pages#home'
  # create routes for users
  resources :users, :except => [:destroy]
  # create routes for movies
  resources :movies
  # # create routes for favorites
  resources :favorites
  # # create routes for reviews
  resources :reviews

  # create route for games
  resources :games, :only => [:index]

  get '/magic' => 'magic#form'
  get '/magic/answer' => 'magic#answer'

  get '/secret' => 'secret#form'
  get '/secret/answer' => 'secret#answer'
  get '/secret/wrong' => 'secret#wrong'

  get '/rockpaperscissor' => 'rockpaperscissor#form'
  get '/rockpaperscissor/answer' => 'rockpaperscissor#answer'
  
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user, :optional => true
    has_and_belongs_to_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_and_belongs_to_many :favorites
    has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :movie, :optional => true
    belongs_to :user, :optional => true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews
    has_many :favorites
    has_secure_password
    validates :email, :uniqueness => true, :presence => true
    validates :name, :uniqueness => true, :presence => true
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end
end

app/controllers/magic_controller.rb
class MagicController < ApplicationController
  def form
  end

  def answer
      @question = params[:question]
      options = ["Certain it is", "Your eyes deceive you. Don't trust them", "In a dark place we find ourselves, and a little more knowledge lights our way", "Difficult to see. Always in motion is the future", "That is true, from a certain point of view", "Control, control, you must learn control", "Yes my master", "Stay on target", "The dark side clouds everything. Impossible to see, the future is", "Already know you that which you need", "I find you lack of faith disturbing", "You must unlearn what you have learned", "Do or do not, there is no try", "Hmm. To a dark place, this line of thought will carry you. Great care you must take", "Feel the force", "There is no such thing as luck", "I have a bad feeling about this", "You will find only what you take with you", "you will know when you are calm... at peace", "already know you, that which you need", "Strong enough, you are not", "Use your feelings", "Clear your mind must be", "Already know you, that which you need"
      ]
      @result = "#{options.sample}"
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def create 
    movie = Movie.create movie_params
    redirect_to movie
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    movie = Movie.find params[:id]
    movie.update movie_params
    redirect_to movie
  end

  def show
    @movie = Movie.find params[:id]
  end

  def destroy
    movie = Movie.find params[:id]
    movie.destroy
    redirect_to movies_path
  end

  private
  def movie_params
    params.require(:movie).permit(:title, :director, :year, :age, :score, :image, :location, :synopsis)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :check_for_login
  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end

  def create
    review = Review.create review_params
    # review mixtapes video to understand what this does
    @current_user.reviews << review
    redirect_to review.movie # GET to show
  end

  def edit
    @review = Review.find params[:id]
  end

  def update 
    review = Review.find params[:id]
    review.update review_params
    redirect_to review # GET to show
  end

  def show
    @review = Review.find params[:id]

  end

  def destroy
    review = Review.find params[:id]
    review.destroy
    redirect_to reviews_path
  end

  private 
  def review_params
      params.require(:review).permit(:title, :comment, :movie_id, :movie_title)
  end
end

app/controllers/secret_controller.rb
class SecretController < ApplicationController
  def form
  end

  def answer
      @guess = params[:num].to_i
      @randnum = rand(10)

      if @guess == @randnum
          render :answer
      else
          render :wrong
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, :only => [:index] # only the index function will run to check for admin. This will ignore all the other functions on this page
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    user = User.find params[:id]
    user.update user_params
    redirect_to root_path
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id # log in the newly created user
      redirect_to movies_path # send the user to a better page
    else
      render :new
   end
  end

  def show
  end

  private
  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/magic_helper.rb
module MagicHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/secret_helper.rb
module SecretHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/index.html.erb
<%# <div class="gameshp">
<h1 class="text-white">Games Homepage</h1>
 <nav>
      <a href="/magic">Magic 8 Ball</a>
      <a href="/secret">Guess the Number</a>
      <a href="/rockpaperscissor">Rock, Paper, Scissors, Lizard, Spock</a>
    </nav>
</div> %>

<div class="gameshp">
    <div class="container">
      <%# <h1 class="text-white">Games</h1> %>
      <div class="row justify-content-around">
            <div class="col-4">
                <h3>Star Wars Game</h3>
                <%= link_to magic_path do %>
                    <%= image_tag "https://i.pinimg.com/originals/41/9e/e3/419ee367eaf14d97306a6e0e7c0804f0.jpg" , :class => 'poster' %>
                <% end %>
            </div>
            <div class="col-4">
                <h3>Saw Game</h3>
                <%= link_to secret_path do %>
                    <%= image_tag "https://bloody-disgusting.com/wp-content/uploads/2018/06/saw-the-game-img6.jpg", :class => 'poster' %>
                <% end %>
            </div>
            <div class="col-4">
                <h3>Star Trek Game</h3>
                <%= link_to rockpaperscissor_path do %>
                    <%= image_tag "https://qph.fs.quoracdn.net/main-qimg-56edbfe92273c68f6949bddddc08d19a-c", :class => 'poster' %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/magic/answer.html.erb
<div class="swbg">
    <h2 class = "sw">
        <% if @current_user.present? %>
            <%= "#{@current_user.name}, this answer you have received:" %>
        <% else %>
            <%= "This answer you have received:" %>
        <% end %>
    </h2>
    <h1 class="dash">------------------------</h1>
    <h2>
        <%= @result %>
    </h2>
</div>

app/views/magic/form.html.erb
 <div class="magic">
    <h1 class = "magic_title">Magic 8 Ball - Star Wars Edition</h1>

    <div class="container">
        <div class="row justify-content-around">
            <div class="col-6">
                <%= image_tag "yoda.gif", :class => "yoda" %>
            </div>
            <div class="col-6">
                <div>
                    <form action="/magic/answer"> 
                            <label class = "form-label">
                                <input class = "form-control", type="search" name="question" placeholder="Ask your question here" required autofocus>
                            </label>
                            <button class = "btn btn-light">Submit</button>
                    </form>
                </div>
            </div>
        <div>
    </div>
</div>

app/views/movies/_form.html.erb
<div class="form">
    <%= form_for @movie do |f| %>
        <%= f.label :title, :class => 'custom_label' %>
        <%= f.text_field :title, :class => 'form-control' %>
        <%= f.label :age, :class => 'custom_label' %>
        <%= f.text_field :age, :class => 'form-control' %>
        <%= f.label :director, :class => 'custom_label' %>
        <%= f.text_field :director, :class => 'form-control' %>
        <%= f.label :year, 'Year of release', :class => 'custom_label' %>
        <%= f.text_field :year, :placeholder => "YYYY", :class => 'form-control' %>
        <%= f.label :score, "iMDb Score", :class => 'custom_label' %>
        <%= f.text_field :score, :placeholder => '5.0', :class => 'form-control' %>
        <%= f.label :location, "Where to watch", :class => 'custom_label' %>
        <%= f.text_field :location, :placeholder => "Disney+", :class => 'form-control' %>
        <%= f.label :synopsis, :class => 'custom_label' %>
        <%= f.text_field :synopsis, :class => 'form-control' %>
        <%= f.label :image, :class => 'custom_label' %>
        <%= f.url_field :image, :required => true, :class => 'form-control' %>
        <%# this replaces the button to submit the form %>

        <%# <%= f.label :review_id %>
        <%# <%= f.select :review_id, Review.pluck(:title, :id), :include_blank => true %>

        <%= f.submit "Submit", :class => 'btn btn-success' %>
    <% end %>
</div>

app/views/movies/edit.html.erb
<div class="adminbg">
    <h1>Edit movie</h1>

    <%= render :partial => 'form' %>
</div>

app/views/movies/index.html.erb
<div class="movies">
    <h1>All movies</h1>

<%# add search functionality for finding movies quickly %>
<%# <form class="d-flex" role="search">
    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success" type="submit">Search</button>
</form> %>
    <section class="mp">
    <% @movies.each do |movie| %>
        <%= link_to image_tag(movie.image, :class => 'thumb' ), movie %>
    <% end %>
    </section>  
</div>

app/views/movies/new.html.erb
 <div class="adminbg">
    <h1>New movie</h1>

    <%= render :partial => 'form' %>
</div>

app/views/movies/show.html.erb
<div class="movie">
    <%# <h1 class="movie_titles"><%= @movie.title </h1>%> 
    <div class="movie_page">
        <%= image_tag @movie.image, :class => 'feature' %>

        <ul class ="movie_details">
            <li>Title: <%= @movie.title %></li>
            <li>Director: <%= @movie.director %></li>
            <li>Year Of Release: <%= @movie.year %></li>
            <li>Age Rating: <%= @movie.age %></li>
            <li>iMDb Score: <%= @movie.score %></li>
            <li>Where To Watch: <%= @movie.location %></li>
            <li>Synopsis: <%= truncate @movie.synopsis, :length => 1000 %></li>
            <div class="preview">Reviews: 
                <% @movie.reviews.each do |review| %>
                    <%# <li class="review">Review: <%= review.title </li>%>
                    <li class="review">💬: <%= review.comment %></li>
                <% end %>
            </div>
        </ul>
    </div>
    <div class="controls">
        <% if @current_user.present?%>
            <% if @current_user.admin? %>
                <%= link_to 'Edit movie', edit_movie_path(@movie), :class => 'links' %>
                <%= link_to 'Delete movie', @movie, :method => 'delete', :data => { :confirm => 'Are you sure' }, :class => 'links' %>
            <% end %>
        <% end %>
    </div>
</div>

app/views/reviews/_form.html.erb
<div class="form">
    <%= form_for @review do |f| %>
        <%= f.label :title, :class => 'custom_label' %>
        <%= f.text_field :title, :class => 'form-control' %>
        <%= f.label :comment, :class => 'custom_label' %>
        <%= f.text_field :comment, :class => 'form-control' %>
        <%= f.label :movie_id, :class => 'custom_label' %>
        <%= f.select :movie_id, Movie.pluck(:title, :id), :include_blank => false, :class => 'form-control' %> 
        <%# this replaces the button to submit the form %>
        <%= f.submit 'Submit', :class => 'btn btn-success' %>
    <% end %>
    </div>

app/views/reviews/edit.html.erb
<div class="adminbg">
    <h1>Edit review</h1>

    <%= render :partial => 'form' %>
</div>

app/views/reviews/index.html.erb
<% if @current_user.present?%>
    <% if @current_user.admin? %>
        <h1>All Reviews</h1>
            <% @reviews.each do |review| %>
            <ul>
                <li>Name: <%= link_to review.title, review %></li>
                <li>Movie: <%= review.movie.title %></li>
                <li>Comment: <%= review.comment %></li>
            </ul>
            <% end %>
    <% else %>
    <h1>My Reviews</h1>
        <% @current_user.reviews.each do |review|%>
        <ul>
            <li>Name: <%= link_to review.title, review %></li>
            <li>Movie: <%= review.movie.title %></li>
            <li>Comment: <%= review.comment %></li>
        </ul>
        <% end %>
    <% end %>
<% end %>

app/views/reviews/new.html.erb
<div class="adminbg">
    <h1>New review</h1>

    <%= render :partial => 'form' %>
</div>

app/views/reviews/show.html.erb
<div class="reviews">
    <h1></h1>

    <ul>
        <li>Title: <%= @review.title %></li>
        <li>Movie: <%= @review.movie.title %></li>
        <li>Comment: <%= @review.comment %></li>
    </ul>
    <% if @review.present? %>
        <% if @review.movie.image.present? %>
        <%= link_to image_tag(@review.movie.image, :class => 'thumb1'), @review.movie %>
        <% end %>
    <% end%>
    <div class="container">
        <%= link_to 'Edit review', edit_review_path(@review) %>
        <%= link_to 'Delete review', @review, :method => 'delete', :data => { :confirm => 'Are you sure?' } %>
    </div>
</div>

app/views/secret/answer.html.erb
<div class="sawwonpage">
    <h1 class="won">
        <%= "Congratulations!" %>
    </h1>
    <h3 class="congrats">
        <%= "You chose correctly and you Are Still Alive. Most People Are So Ungrateful To Be Alive... But Not You, Not Anymore!" %>
    </h3>
</div>

app/views/secret/form.html.erb
<div class="secret">
    <% if @current_user.present? %>
        <h1 class = "sawtext">Hello <%= @current_user.name %>,</h1>
    <% else %>
        <h1 class = "sawtext">Hello, </h1> 
    <% end%>
    <h3 class = "sawtext">I'm sure you're wondering why you're here. You deny culpability, no doubt, for the circumstances in which you find yourself. However salvation can be yours. Select a number between 1 and 10, the choice is yours, but failure to make the right choice could result in death.</h3>
     <form action="/secret/answer" method="get"> 
        <div class="sttrek">
            <button class = "saw_button" name="num" type="submit" value=1>1</button>
            <button class = "saw_button" name="num" type="submit" value=2>2</button>
            <button class = "saw_button" name="num" type="submit" value=3>3</button>
            <button class = "saw_button" name="num" type="submit" value=4>4</button>
            <button class = "saw_button" name="num" type="submit" value=5>5</button>
            <button class = "saw_button" name="num" type="submit" value=6>6</button>
            <button class = "saw_button" name="num" type="submit" value=7>7</button>
            <button class = "saw_button" name="num" type="submit" value=8>8</button>
            <button class = "saw_button" name="num" type="submit" value=9>8</button>
            <button class = "saw_button" name="num" type="submit" value=10>10</button>
        </div>
    </form>
    <%= image_tag "secrethp.gif", :class => 'rules' %>
</div>


<%# <form action="/secret/answer"> 
        <label class="reducelabel"><input type="search" name="num" placeholder="1, 2,... 8, 9" required autofocus></label>
        <button >Live Or Die. Make Your Choice</button>
    </form> %>

app/views/secret/wrong.html.erb
<div class = "loser" >
    <h1 class="lost">
        <%= "Game Over!" %>
    </h1>
    <img class ="saw", src="https://i.pinimg.com/originals/78/32/d9/7832d9cf69cb94c9b64b2bdb4d4205d5.gif" alt="Head crush">
</div>