config/routes.rb
Rails.application.routes.draw do
  # create path to homepage
  root :to => 'pages#home'
  # create routes for users
  resources :users, :except => [:destroy]
  # create routes for movies
  resources :movies
  # # create routes for favorites
  resources :favorites
  # # create routes for reviews
  resources :reviews

  # create route for games
  resources :games, :only => [:index]

  get '/magic' => 'magic#form'
  get '/magic/answer' => 'magic#answer'

  get '/secret' => 'secret#form'
  get '/secret/answer' => 'secret#answer'
  get '/secret/wrong' => 'secret#wrong'

  get '/rockpaperscissor' => 'rockpaperscissor#form'
  get '/rockpaperscissor/answer' => 'rockpaperscissor#answer'
  
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user, :optional => true
    has_and_belongs_to_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_and_belongs_to_many :favorites
    has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :movie, :optional => true
    belongs_to :user, :optional => true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews
    has_many :favorites
    has_secure_password
    validates :email, :uniqueness => true, :presence => true
    validates :name, :uniqueness => true, :presence => true
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end
end

app/controllers/magic_controller.rb
class MagicController < ApplicationController
  def form
  end

  def answer
      @question = params[:question]
      options = ["Certain it is", "Your eyes deceive you. Don't trust them", "In a dark place we find ourselves, and a little more knowledge lights our way", "Difficult to see. Always in motion is the future", "That is true, from a certain point of view", "Control, control, you must learn control", "Yes my master", "Stay on target", "The dark side clouds everything. Impossible to see, the future is", "Already know you that which you need", "I find you lack of faith disturbing", "You must unlearn what you have learned", "Do or do not, there is no try", "Hmm. To a dark place, this line of thought will carry you. Great care you must take", "Feel the force", "There is no such thing as luck", "I have a bad feeling about this", "You will find only what you take with you", "you will know when you are calm... at peace", "already know you, that which you need", "Strong enough, you are not", "Use your feelings", "Clear your mind must be", "Already know you, that which you need"
      ]
      @result = "#{options.sample}"
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def create 
    movie = Movie.create movie_params
    redirect_to movie
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    movie = Movie.find params[:id]
    movie.update movie_params
    redirect_to movie
  end

  def show
    @movie = Movie.find params[:id]
  end

  def destroy
    movie = Movie.find params[:id]
    movie.destroy
    redirect_to movies_path
  end

  private
  def movie_params
    params.require(:movie).permit(:title, :director, :year, :age, :score, :image, :location, :synopsis)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, :only => [:index] # only the index function will run to check for admin. This will ignore all the other functions on this page
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    user = User.find params[:id]
    user.update user_params
    redirect_to root_path
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id # log in the newly created user
      redirect_to movies_path # send the user to a better page
    else
      render :new
   end
  end

  def show
  end

  private
  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/magic_helper.rb
module MagicHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/secret_helper.rb
module SecretHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="">
      <nav class="navbar navbar-expand-lg bg-body-tertiary navbar-dark">
        <div class="container-fluid">
          <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
            <ul class="navbar-nav mb-2 mb-lg-0">
              <li class="nav-item">
                <%= link_to "Home", root_path, :class => 'nav-link active' %>
                <%# Link for home page always seen %>
              </li>
              <li class="nav-item">
                <%= link_to 'Movies', movies_path, :class => 'nav-link active' %>
                <%# link for movies page only seen when away from home page %>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="/games" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Games
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Star Wars Game', magic_path, :class => 'dropdown-item' %></li>
                  <li><%= link_to 'Saw Game', secret_path, :class => 'dropdown-item' %></li>
                  <li><%= link_to 'Star Trek Game', rockpaperscissor_path, :class => 'dropdown-item' %></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="/games" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Account
                </a>
                <ul class="dropdown-menu">
                  <% if @current_user.present?%>
                    <% if @current_user.admin? %>
                      <li><%=link_to "All users", users_path, :class => 'dropdown-item' %></li>
                      <li><%= link_to "All reviews", reviews_path, :class => 'dropdown-item' %></li>
                      <li><%= link_to "New Movie", new_movie_path, :class => 'dropdown-item' %></li>
                    <% else %>
                      <li><%= link_to "My Reviews", reviews_path, :class => 'dropdown-item' %></li>
                    <% end %>
                    <li><%= link_to "New Review", new_review_path, :class => 'dropdown-item' %></li>
                    <li><%= link_to 'Update my details', edit_user_path(@current_user), :class => 'dropdown-item' %></li>
                    <li><%= link_to "Sign out", login_path, :method => 'delete', :class => 'dropdown-item' %></li>
                  <% else %>
                    <li><%= link_to 'Sign up', new_user_path, :class => 'dropdown-item' %></li>
                    <li><%= link_to 'Log in', login_path, :class => 'dropdown-item' %></li>
                  <% end%>
                </ul>
              </li>
          </div>
        </div>
      </nav>
      <%= yield %>
      </div>
  </body>
</html>
        <!--nav>
          <%= link_to_unless_current 'Home', root_path %>
          <%= link_to_unless_current 'Movies', movies_path %>
          <%= link_to_unless_current  'Games', games_path %>

          <% if @current_user.present?%>
            <% if @current_user.admin? %>
              <%=link_to "All users", users_path %>
              <%= link_to "All reviews", reviews_path %>
            <% else %>
              <%= link_to "My Reviews", reviews_path %>
          <% end %>
          <%= link_to "New Review", new_review_path%>
          <%# <%= link_to 'My Favorites Lists', new_artist_path %>
          <%= link_to "Sign out' #{ @current_user.email }", login_path, :method => 'delete' %>
          <% else %>
            <%= link_to 'Sign up', new_user_path %>
            <%= link_to 'Log in', login_path %>
          <% end%>
        </nav-->

app/views/pages/home.html.erb
<div class="homepage">
    <div class="container">
    <p class="text-center">Welcome to my page where you can play movie themed games or browse movies to see user reviews and if you sign up to an account, you can create and post your own reviews for the movies of your choice. </p>
        <div class="row justify-content-around">
            <div class="col-4">
                <h2>Review Movies</h2>
                <%= link_to movies_path do %>
                    <%= image_tag "https://th.bing.com/th/id/OIP.bnFi87faJToMxTXny-FAKAHaEK?pid=ImgDet&rs=1" , :class => 'poster' %>
                <% end %>
            </div>
            <div class="col-4">
                <h2>Play Games</h2>
                <%= link_to games_path do %>
                    <%= image_tag "https://wallpapercave.com/wp/wp3748776.jpg", :class => 'poster' %>
                <% end %>
            </div>
        </div>
    </div>
</div>